Repository ServerIbraimovUa/movies_project, pull requests merged in 2024-02, with the labels that each got.

#64 Create css
  src/assets/fonts.d.ts
  src/assets/fonts/WorkSans/WorkSans-Medium.ttf
  src/assets/fonts/WorkSans/WorkSans-Regular.ttf
  src/assets/fonts/WorkSans/WorkSans-SemiBold.ttf
  src/assets/fonts/ZenMaruGothic/ZenMaruGothic-Bold.ttf
  src/assets/fonts/ZenMaruGothic/ZenMaruGothic-Medium.ttf
  src/assets/fonts/ZenMaruGothic/ZenMaruGothic-Regular.ttf
  src/css/deviceSize.ts
  src/css/index.ts
  src/index.css
  src/index.tsx
  tsconfig.json
Labels: enhancement

#65 css
  src/assets/images/sprite.svg
  src/css/deviceSize.ts
  src/css/index.ts
  src/pages/DeleteAccount.tsx
  src/pages/EditProfile.tsx
Labels: duplicate

#66 Update index.ts
  src/css/index.ts
Labels: enhancement

#69 Styled user modal
  package-lock.json
  src/assets/fonts.d.ts
  src/assets/images/sprite.svg
  src/components/Actor/ActorCredits/ActorCredits.styled.tsx
  src/components/App.tsx
  src/components/Home/Sidebar/Sidebar.styled.tsx
  src/components/Layout/Layout.styled.ts
  src/components/Layout/Layout.tsx
  src/components/SettingsMobModal/SettingMobModal.styled.ts
  src/components/SettingsMobModal/SettingsMobModal.tsx
  src/components/SettingsMobModal/settingsMobModal.css
  src/components/UserModal/SocialLink.tsx
  src/components/UserModal/UserModal.styled.ts
  src/components/UserModal/UserModal.tsx
  src/components/UserModal/userModal.css
  src/css/index.css
  src/css/index.ts
  src/pages/ActorPage.tsx
  src/pages/Settings.tsx
  src/pages/Settings/Settings.styled.ts
  src/pages/Settings/Settings.tsx
  src/types/index.d.ts
  src/types/userModalTypes.ts
Labels: duplicate, enhancement

#73 Movie details branch
  src/components/Cast/CastItem/CastItem.styled.js
  src/components/Cast/CastList/CastClick.css
  src/components/Cast/CastList/CastList.styled.js
  src/components/Layout/Layout.tsx
  src/components/MovieDetails/Cast/Cast.styled.ts
  src/components/MovieDetails/Cast/Cast.tsx
  src/components/MovieDetails/Cast/CastItem/CastItem.styled.ts
  src/components/MovieDetails/Cast/CastItem/CastItem.tsx
  src/components/MovieDetails/Cast/CastList/CastList.tsx
  src/components/MovieDetails/MovieDetails.styled.ts
  src/components/MovieDetails/MovieDetails.tsx
  src/components/MovieDetails/MovieDetailsItem/MovieDetailsItem.tsx
  src/components/MovieDetails/MovieTrailer/MovieTrailer.styled.ts
  src/components/MovieDetails/MovieTrailer/MovieTrailer.tsx
  src/components/MovieDetails/Recommendations/Recommendations.styled.ts
  src/components/MovieDetails/Recommendations/Recommendations.tsx
  src/components/MovieDetails/Recommendations/RecommendationsItem/RecommendationsItem.tsx
  src/components/MovieDetails/Recommendations/RecommendationsList/RecommendationsClick.css
  src/components/MovieDetails/Recommendations/RecommendationsList/RecommendationsList.tsx
  src/components/MovieDetails/Reviews/Reviews.tsx
  src/components/MovieDetails/Reviews/ReviewsItem/ReviewsItem.styled.ts
  src/components/MovieDetails/Reviews/ReviewsItem/ReviewsItem.tsx
  src/components/MovieDetails/Reviews/ReviewsList/ReviewsList.styled.ts
  src/components/MovieDetails/Reviews/ReviewsList/ReviewsList.tsx
  src/components/MovieDetails/Reviews/SeeMoreBtn/SeeMoreBtn.styled.ts
  src/components/MovieDetails/Reviews/SeeMoreBtn/SeeMoreBtn.tsx
  src/components/Recommendations/RecommendationsList/RecommendationsList.styled.js
  src/components/UpcomingList/UpcomingListSlick.css
  src/components/UpcomingList/UpcomingListSlick.styled.tsx
  src/components/UpcomingList/UpcomingListSlick.tsx
  src/pages/MovieDetailsPage.tsx
  src/pages/PagesStyles/MovieDetailPage.styled.js
Labels: enhancement

#75 finished styles for movieDetails Component
  public/userAvatar.png
  src/Language/Json/en.json
  src/components/Layout/Layout.tsx
  src/components/MovieDetails/Cast/Cast.styled.ts
  src/components/MovieDetails/Cast/CastItem/CastItem.styled.ts
  src/components/MovieDetails/Cast/CastItem/CastItem.tsx
  src/components/MovieDetails/Cast/CastList/CastList.styled.ts
  src/components/MovieDetails/Cast/CastList/CastList.tsx
  src/components/MovieDetails/MovieDetails.styled.ts
  src/components/MovieDetails/MovieDetails.tsx
  src/components/MovieDetails/MovieTrailer/MovieTrailer.tsx
  src/components/MovieDetails/Recommendations/Recommendations.tsx
  src/components/MovieDetails/Recommendations/RecommendationsItem/RecommendationsItem.tsx
  src/components/MovieDetails/Recommendations/RecommendationsList/RecommendationsList.tsx
  src/components/MovieDetails/Reviews/Reviews.tsx
  src/components/MovieDetails/Reviews/ReviewsItem/ReviewsItem.styled.ts
  src/components/MovieDetails/Reviews/ReviewsItem/ReviewsItem.tsx
  src/components/MovieDetails/Reviews/ReviewsList/ReviewsList.tsx
  src/components/MovieDetails/Reviews/SeeMoreBtn/SeeMoreBtn.styled.ts
  src/components/MovieDetails/Reviews/SeeMoreBtn/SeeMoreBtn.tsx
  src/pages/ActorPage/ActorPage.styled.tsx
  src/pages/MovieDetailsPage.tsx
  src/pages/PagesStyles/MovieDetailPage.styled.js
Labels: enhancement
